[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
parse_mediawiki_dump_reboot = "1.0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
